"""Flutter test runner rule.

Compiles a Flutter test entry point to a kernel `.dill` and runs it under
`flutter_tester`, the headless Flutter engine. Tests interact with the test
runner via the same `package:test_api/backend.dart` `RemoteListener`
protocol that `flutter test` uses, so widget tests that initialize
`TestWidgetsFlutterBinding` (every `testWidgets`, every golden, the live
binding) work.

Wire-up:
  1. Bazel writes a per-target bootstrap `<name>_bootstrap.dart` that imports
     the user's test as `test`, then calls `RemoteListener.start(() => test.main)`
     and pipes the resulting StreamChannel over a WebSocket to the runner.
  2. The user's test + bootstrap are compiled together to a kernel `.dill` via
     the standard frontend_server (debug platform dill, `--enable-asserts`).
  3. The runner binary spawns `flutter_tester` with the dill, hosts a localhost
     WebSocket harness, drives the `package:test` MultiChannel protocol, and
     reports per-test pass/fail.

Coverage: when `bazel coverage` sets `COVERAGE_OUTPUT_FILE`, the runner
launches `flutter_tester` with the VM service enabled and collects source
reports via JSON-RPC, writing LCOV.

Usage:
    flutter_test(
        name = "widget_test",
        main = "test/widget_test.dart",
        deps = [
            "@deps//:flutter",
            "@deps//:flutter_test",
            "//:my_app_lib",
        ],
    )

The user's `deps` must transitively expose `package:flutter_test` (and
therefore `package:test_api`) so the generated bootstrap compiles.
"""

load("@rules_dart//dart:providers.bzl", "DartInfo")
load("@rules_dart//dart:utils.bzl", "COPY_TO_DIRECTORY_TOOLCHAINS", "collect_packages", "collect_transitive_srcs", "dart_analyzable_info", "dart_analyzable_info_with_package", "derive_lib_root", "runfiles_path")
load("//flutter:providers.bzl", "FlutterInfo")
load(
    "//flutter/private:app_entrypoint.bzl",
    "compile_package_config",
    "synthesize_app_package",
)
load(
    "//flutter/private:common.bzl",
    "FLUTTER_APPLICATION_ATTRS",
    "PLATFORM_CONSTRAINT_ATTRS",
    "detect_target_platform",
    "flutter_build_assets",
    "flutter_compile_shaders",
    "host_target_arch",
    "merge_dart_defines",
)
load("//flutter/private:flutter_compile.bzl", "flutter_cfe_uri", "flutter_kernel_compile_action")
load("//flutter/private:flutter_native_assets.bzl", "bridge_dart_code_assets", "collect_bundled_code_asset_files", "write_native_assets_manifest")

def _make_bootstrap_content(test_relative_import):
    """Generate the per-test bootstrap Dart source.

    The bootstrap is the kernel entry point flutter_tester loads. It calls
    `RemoteListener.start(() => test.main)` to register the user's tests with
    `package:test_api`, then opens a WebSocket back to the harness on
    `FLUTTER_TEST_HARNESS_PORT` and forwards the resulting channel as
    JSON-encoded `[id, data]` tuples (the `package:stream_channel`
    MultiChannel framing the test harness already speaks).

    Args:
        test_relative_import: Path-style import URI from the bootstrap file
            to the user's test source (e.g. `../../e2e/foo/test/widget_test.dart`).

    Returns:
        Dart source string.
    """
    return """// GENERATED by flutter_test — do not edit.
//
// Bootstraps a Flutter widget test under flutter_tester. Connects back to
// the bazel-side harness over WebSocket and drives the test via
// package:test_api/backend.dart RemoteListener — the same surface
// `flutter test` uses.
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:test_api/backend.dart';

import '{test_import}' as test;

void _catchIsolateErrors() {{
  final errorPort = ReceivePort();
  Isolate.current.setErrorsFatal(false);
  Isolate.current.addErrorListener(errorPort.sendPort);
  errorPort.listen((dynamic message) {{
    final list = message as List;
    final error = IsolateSpawnException(list[0] as String);
    final stack = list[1] == null
        ? StackTrace.empty
        : StackTrace.fromString(list[1] as String);
    Zone.current.handleUncaughtError(error, stack);
  }});
}}

Future<void> _runTestMain() async {{
  await Future(test.main);
}}

Future<void> main() async {{
  final portStr = Platform.environment['FLUTTER_TEST_HARNESS_PORT'];
  if (portStr == null || portStr.isEmpty) {{
    stderr.writeln('flutter_test bootstrap: FLUTTER_TEST_HARNESS_PORT not set');
    exit(64);
  }}
  final port = int.parse(portStr);

  final testChannel = RemoteListener.start(() {{
    _catchIsolateErrors();
    return _runTestMain;
  }});

  final ws = await WebSocket.connect('ws://127.0.0.1:$port');
  // Forward harness → testChannel. `pipe` completes when the WebSocket
  // closes; we don't need to await it because the harness side closes the
  // socket once the suite is done.
  unawaited(ws.map<dynamic>((dynamic m) => json.decode(m as String))
      .pipe(testChannel.sink));
  // Forward testChannel events → harness. `addStream` completes when the
  // testChannel's stream is done — that happens after the harness sends
  // a close message and RemoteListener closes the inner controller. At
  // that point we exit the isolate explicitly so flutter_tester shuts
  // down without waiting for the engine to drain its event loop.
  await ws.addStream(testChannel.stream.map<String>((dynamic m) => json.encode(m)));
  exit(0);
}}
""".format(test_import = test_relative_import)

def _has_flutter_test(deps):
    """True if any dep transitively exposes package:flutter_test or package:test_api."""
    for dep in deps:
        if DartInfo not in dep:
            continue
        for pkg in dep[DartInfo].transitive_packages.to_list():
            if pkg.package_name == "flutter_test" or pkg.package_name == "test_api":
                return True
    return False

def partition_analyzable_sources(srcs, lib_root):
    """Splits direct test sources into package lib files and support files."""
    lib_prefix = (lib_root + "/" if lib_root else "") + "lib/"
    package_srcs = []
    support_srcs = []
    for src in srcs:
        if src.short_path.startswith(lib_prefix):
            package_srcs.append(src)
        else:
            support_srcs.append(src)
    return (package_srcs, support_srcs)

def _flutter_test_impl(ctx):
    flutter_toolchain = ctx.toolchains["@rules_flutter//flutter:toolchain_type"]
    flutter_sdk_info = flutter_toolchain.flutter_sdk_info

    if not flutter_sdk_info.flutter_tester:
        fail(
            "flutter_test requires the active Flutter toolchain to provide a " +
            "flutter_tester binary; the resolved toolchain has none. This is " +
            "typically the case for cross-compile-only configurations — " +
            "build the test target with the host platform.",
        )

    if not _has_flutter_test(ctx.attr.deps):
        fail((
            "flutter_test target {name} must depend on package:flutter_test " +
            "(or at minimum package:test_api). Add `@<hub>//:flutter_test` " +
            "to deps so the generated bootstrap can import RemoteListener."
        ).format(name = ctx.label.name))

    # Per-target bootstrap. Import the user's test through the same stable CFE
    # filesystem URI space used for every compilation input. A relative import
    # from bazel-out can escape to the wrong URI root for nested Bazel packages.
    bootstrap = ctx.actions.declare_file(ctx.label.name + "_bootstrap.dart")
    test_import = flutter_cfe_uri(ctx.file.main.path)
    ctx.actions.write(bootstrap, _make_bootstrap_content(test_import))

    # Collect transitive Dart sources and packages for the kernel compile.
    # Only package-owned lib/ sources may enter package colocation. Test
    # entrypoints/support files and the generated bootstrap live outside lib/;
    # allowing a nested package root to claim them would move them into the
    # assembled package tree while the bootstrap still imports their logical
    # source path.
    app_lib_root = derive_lib_root(ctx.label.workspace_root, ctx.label.package)
    direct_srcs = depset(direct = list(ctx.files.srcs) + [ctx.file.main]).to_list()
    package_direct_srcs, support_direct_srcs = partition_analyzable_sources(direct_srcs, app_lib_root)
    package_inputs = collect_transitive_srcs(ctx.attr.deps).to_list() + package_direct_srcs
    packages = collect_packages(ctx.attr.deps)

    # Register the test's own package (when declared) so `package:<self>/foo`
    # imports inside test sources resolve, then co-locate any package whose
    # hand-written + generated sources straddle the source tree and bazel-out
    # so `part` directives and the package's single rootUri resolve. Without
    # the colocation, a test that imports `package:<self>/foo.dart` fails to
    # find foo.dart's generated `.g.dart` / `.freezed.dart` siblings.
    packages = synthesize_app_package(packages, ctx.attr.package_name, app_lib_root)
    pc = compile_package_config(ctx, packages, package_inputs)
    package_config = pc.config_file
    all_srcs = pc.srcs + support_direct_srcs + [bootstrap]

    # Tests execute on the host under flutter_tester. Resolve that platform
    # before kernel compilation because frontend_server must embed the Native
    # Assets manifest into the dill.
    is_macos = ctx.target_platform_has_constraint(
        ctx.attr._macos_constraint[platform_common.ConstraintValueInfo],
    )
    is_ios = ctx.target_platform_has_constraint(
        ctx.attr._ios_constraint[platform_common.ConstraintValueInfo],
    )
    is_linux = ctx.target_platform_has_constraint(
        ctx.attr._linux_constraint[platform_common.ConstraintValueInfo],
    )
    is_windows = ctx.target_platform_has_constraint(
        ctx.attr._windows_constraint[platform_common.ConstraintValueInfo],
    )
    is_android = ctx.target_platform_has_constraint(
        ctx.attr._android_constraint[platform_common.ConstraintValueInfo],
    )
    target_platform = detect_target_platform(is_ios, is_macos, is_linux, is_windows, is_android)

    # Mirror flutter_application's Native Assets aggregation. In particular,
    # this lifts rules_dart's curated replacements (such as sqlite3) from the
    # Dart package graph without requiring the test to name a native target.
    transitive_native_asset_depsets = []
    for dep in ctx.attr.deps:
        if FlutterInfo not in dep:
            continue
        info = dep[FlutterInfo]
        if hasattr(info, "native_assets") and info.native_assets != None:
            transitive_native_asset_depsets.append(info.native_assets)
    native_assets_list = depset(transitive = transitive_native_asset_depsets).to_list()
    declared_ids = {asset.asset_id: True for asset in native_assets_list}
    native_assets_list = native_assets_list + [
        asset
        for asset in bridge_dart_code_assets(ctx, ctx.attr.deps)
        if asset.asset_id not in declared_ids
    ]

    native_assets_manifest = ctx.actions.declare_file(ctx.label.name + ".native_assets.json")
    write_native_assets_manifest(
        ctx = ctx,
        output_file = native_assets_manifest,
        native_assets = native_assets_list,
        target_os = target_platform,
        target_arch = host_target_arch(ctx, flutter_sdk_info),
    )
    bundled_code_assets = collect_bundled_code_asset_files(native_assets_list).to_list()

    # Native Asset manifest entries intentionally contain stable basenames,
    # not checkout- or output-base-dependent absolute paths. Stage every
    # bundled library in one test-private directory and launch flutter_tester
    # there so the VM can resolve those basenames at runtime.
    native_asset_runtime_files = []
    native_asset_basenames = {}
    for asset in bundled_code_assets:
        if asset.basename in native_asset_basenames:
            fail(
                "flutter_test %s has two bundled native assets named %s (%s and %s)" % (
                    ctx.label,
                    asset.basename,
                    native_asset_basenames[asset.basename].short_path,
                    asset.short_path,
                ),
            )
        native_asset_basenames[asset.basename] = asset
        staged = ctx.actions.declare_file(ctx.label.name + "_native_assets/" + asset.basename)
        ctx.actions.symlink(output = staged, target_file = asset)
        native_asset_runtime_files.append(staged)

    # Compile bootstrap+test to kernel using the debug platform dill (asserts on).
    kernel_dill = ctx.actions.declare_file(ctx.label.name + ".dill")
    flutter_kernel_compile_action(
        ctx = ctx,
        dartaotruntime = flutter_sdk_info.dartaotruntime,
        flutter_sdk_files = flutter_sdk_info.tool_files,
        frontend_server = flutter_sdk_info.frontend_server,
        platform_dill = flutter_sdk_info.platform_kernel_dill,
        main = bootstrap,
        srcs = all_srcs,
        package_config = package_config,
        output = kernel_dill,
        aot = False,
        defines = merge_dart_defines(ctx),
        target = "flutter",
        native_assets_manifest = native_assets_manifest,
    )

    # Build a `flutter_assets/` tree for the test. Material widgets pull
    # `shaders/ink_sparkle.frag` at first paint, and pub-package fonts/assets
    # (e.g. MaterialIcons) need to land in the bundle for tests that resolve
    # them via `rootBundle`. Tests run on the host, so shaders compile against
    # the host platform.
    compiled_shaders = flutter_compile_shaders(ctx, flutter_sdk_info, target_platform)
    flutter_assets = flutter_build_assets(
        ctx,
        flutter_sdk_info,
        compiled_shaders,
        kernel_dill = kernel_dill,
        is_debug = True,
    )

    # Symlink the prebuilt runner as the test executable.
    tool = ctx.attr._tool
    is_windows = ctx.target_platform_has_constraint(
        ctx.attr._windows_constraint[platform_common.ConstraintValueInfo],
    )
    ext = ".exe" if is_windows else ""
    executable = ctx.actions.declare_file(ctx.label.name + ext)
    ctx.actions.symlink(
        output = executable,
        target_file = tool[DefaultInfo].files_to_run.executable,
        is_executable = True,
    )

    # Runfiles-relative paths the runner reads from env at start-up.
    workspace_name = ctx.workspace_name
    env = {
        "FLUTTER_TEST_TESTER": runfiles_path(flutter_sdk_info.flutter_tester, workspace_name),
        "FLUTTER_TEST_ICU": runfiles_path(flutter_sdk_info.icu_data, workspace_name),
        "FLUTTER_TEST_DILL": runfiles_path(kernel_dill, workspace_name),
        "FLUTTER_TEST_ASSETS": runfiles_path(flutter_assets, workspace_name),
        # Display path for the suite. Used in package:test report output.
        "FLUTTER_TEST_PATH": ctx.file.main.short_path,
    }
    if native_asset_runtime_files:
        env["FLUTTER_TEST_NATIVE_ASSET"] = runfiles_path(native_asset_runtime_files[0], workspace_name)
    env_info = testing.TestEnvironment(env)

    runtime_files = [
        kernel_dill,
        flutter_sdk_info.flutter_tester,
        flutter_sdk_info.icu_data,
        flutter_assets,
        native_assets_manifest,
    ] + native_asset_runtime_files
    tool_runfiles = tool[DefaultInfo].default_runfiles
    runfiles = ctx.runfiles(
        files = runtime_files + ctx.files.data,
        transitive_files = flutter_sdk_info.tool_files,
    )
    runfiles = runfiles.merge(tool_runfiles)

    # Merge the runfiles of any `data` targets so cc_library / cc_binary
    # producers (e.g. shared dylibs that the test loads via dart:ffi) and
    # transitively-needed files come along. Mirrors the behavior of
    # rules_dart's dart_binary/dart_test and the standard cc_test/py_test
    # `data` semantics.
    for data_target in ctx.attr.data:
        runfiles = runfiles.merge(data_target[DefaultInfo].default_runfiles)

    instrumented_files_info = coverage_common.instrumented_files_info(
        ctx,
        source_attributes = ["srcs", "main"],
        dependency_attributes = ["deps"],
    )

    package_srcs, support_srcs = partition_analyzable_sources(direct_srcs, app_lib_root)
    if package_srcs:
        analyzable_info = dart_analyzable_info_with_package(
            label = ctx.label,
            package_name = ctx.attr.package_name,
            lib_root = app_lib_root,
            deps = ctx.attr.deps,
            srcs = support_srcs,
            package_srcs = package_srcs,
        )
    else:
        analyzable_info = dart_analyzable_info(
            deps = ctx.attr.deps,
            srcs = support_srcs,
        )

    return [
        DefaultInfo(
            executable = executable,
            runfiles = runfiles,
        ),
        env_info,
        instrumented_files_info,
        analyzable_info,
    ]

# flutter_test takes the compilation attrs plus the asset-bundle attrs.
# Material widgets implicitly require `shaders/ink_sparkle.frag` and the
# MaterialIcons font, so a flutter_assets/ tree is built and passed to
# flutter_tester via `--flutter-assets-dir`. Platform-runner-specific
# attrs (engines, plugin libs) are intentionally omitted — flutter_tester
# is a self-contained host engine.
_TEST_ATTRS = {
    k: v
    for k, v in FLUTTER_APPLICATION_ATTRS.items()
    if k in (
        "main",
        "srcs",
        "deps",
        "defines",
        "_extra_dart_defines",
        "package_name",
        # Asset-bundle inputs. Same surface as flutter_application — most
        # widget tests don't touch these, but Material widgets implicitly
        # require shader and font assets to render.
        "assets",
        "shaders",
        "license_files",
        "tree_shake_icons",
        "_asset_bundle_tool",
    )
}

# Standard `data` attr — files made available at test runtime via
# runfiles. Tests resolve them through `package:runfiles` /
# `Runfiles.create()`. Used for fixtures, golden images, and
# (importantly) FFI shared libraries the test loads via `dart:ffi`.
# Without this, a test that calls into a `cc_library`-produced dylib
# fails at `DynamicLibrary.open` with "file not found", and the
# failure surfaces silently from worker isolates as a hung
# `_opened.future` on the main isolate.
_TEST_ATTRS["data"] = attr.label_list(
    allow_files = True,
    doc = "Runtime data deps. Available in test runfiles. Use for " +
          "fixtures, goldens, and FFI dylibs.",
)
_TEST_ATTRS.update(PLATFORM_CONSTRAINT_ATTRS)
_TEST_ATTRS["_tool"] = attr.label(
    default = Label("//flutter/private/tools:flutter_test_runner"),
    cfg = "exec",
)

flutter_test = rule(
    implementation = _flutter_test_impl,
    attrs = _TEST_ATTRS,
    test = True,
    toolchains = [
        "@rules_flutter//flutter:toolchain_type",
    ] + COPY_TO_DIRECTORY_TOOLCHAINS,
    doc = "Compiles a Flutter widget test, then runs it under flutter_tester " +
          "via the package:test_api RemoteListener protocol.",
)
