"""A `FLUTTER_ROOT`-shaped repository, for resolving pubspec.lock hermetically.

Bazel *consumes* `pubspec.lock` (`flutter.pub()` reads it and creates one repo
per package) but nothing in the build produces it. The toolchain rules_flutter
downloads is engine artifacts plus a Dart SDK — there is no `bin/flutter` and
no `pub` executable in it — so regenerating the lock after editing
`pubspec.yaml` has meant reaching for a separately installed Flutter on `PATH`,
at whatever version that happens to be. A lock resolved by a different SDK than
the one that compiles it is a silent hazard: an older resolver caps packages at
older versions, and nothing afterwards can tell.

The Dart SDK inside the toolchain has `dart pub`, and pub can resolve
`sdk: flutter` dependencies against any directory named by `FLUTTER_ROOT`. It
needs exactly three things from that directory:

  * `packages/<name>/` for each `sdk: flutter` dependency (pub's
    `FlutterSdk.packagePath`),
  * `bin/cache/pkg/sky_engine/`, which `packages/flutter` itself depends on,
  * `bin/cache/flutter.version.json`, whose `flutterVersion` field satisfies
    `environment: flutter:` constraints. Without it pub reports "the Flutter
    SDK is not available" and refuses to resolve at all.

This repository assembles those three from the same GitHub tag tarball
`flutter_sdk_package` already downloads, at the version the toolchain pins. It
is fetched only when `@rules_flutter//flutter:pub` is built, never by a normal
build.
"""

_GITHUB_URL_TEMPLATE = "https://github.com/flutter/flutter/archive/refs/tags/{version}.tar.gz"

_BUILD_TEMPLATE = """# Generated by flutter_dev_root_repo.bzl

# The whole tree, as `dart pub` walks it at run time.
filegroup(
    name = "dev_root",
    srcs = glob(["**"], exclude = ["BUILD.bazel"]),
    visibility = ["//visibility:public"],
)

# The anchor `@rules_flutter//flutter:pub` resolves FLUTTER_ROOT from: it sits
# at a fixed depth (bin/cache/flutter.version.json) below the root.
filegroup(
    name = "version_manifest",
    srcs = ["bin/cache/flutter.version.json"],
    visibility = ["//visibility:public"],
)
"""

def _flutter_dev_root_repo_impl(repository_ctx):
    flutter_version = repository_ctx.attr.flutter_version
    url = _GITHUB_URL_TEMPLATE.format(version = flutter_version)

    # Downloaded once and extracted twice: the two trees pub needs live in
    # different places in the monorepo, and download_and_extract would fetch
    # the archive again for the second one.
    archive = "flutter-{}.tar.gz".format(flutter_version)
    repository_ctx.download(
        url = url,
        sha256 = repository_ctx.attr.sha256,
        output = archive,
    )

    # All of `packages/`, not only the packages rules_flutter builds against:
    # any of them can appear as an `sdk: flutter` dependency in a user's
    # pubspec, and matching a real install is what keeps pub's view of the SDK
    # from drifting away from the real one.
    repository_ctx.extract(
        archive = archive,
        stripPrefix = "flutter-{}/packages".format(flutter_version),
        output = "packages",
    )

    # sky_engine lives with the engine sources in the monorepo, but a real
    # install materializes it under bin/cache/pkg, which is where pub looks.
    repository_ctx.extract(
        archive = archive,
        stripPrefix = "flutter-{}/engine/src/flutter/sky/packages/sky_engine".format(flutter_version),
        output = "bin/cache/pkg/sky_engine",
    )
    repository_ctx.delete(archive)

    # A real install's manifest carries more fields (dartSdkVersion,
    # devToolsVersion, commit dates). Only what rules_flutter actually knows
    # goes in here; inventing the rest would be worse than omitting it, and pub
    # reads only `flutterVersion`.
    repository_ctx.file(
        "bin/cache/flutter.version.json",
        json.encode_indent({
            "flutterVersion": flutter_version,
            "frameworkVersion": flutter_version,
            "engineRevision": repository_ctx.attr.engine_revision,
        }) + "\n",
    )

    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

flutter_dev_root_repo = repository_rule(
    _flutter_dev_root_repo_impl,
    doc = "Assembles a FLUTTER_ROOT-shaped tree for `@rules_flutter//flutter:pub`.",
    attrs = {
        "flutter_version": attr.string(
            mandatory = True,
            doc = "Flutter SDK version, matching a tag in flutter/flutter.",
        ),
        "engine_revision": attr.string(
            doc = "Engine commit recorded in the generated version manifest.",
        ),
        "sha256": attr.string(
            doc = "Checksum of the flutter/flutter tag tarball. Shared with " +
                  "flutter_sdk_package, which fetches the same archive.",
        ),
    },
)
