"""Hub repository aggregating the packages of a single `pubspec.lock`.

`pubspec.lock` records no dependency edges between packages, but it does record
the *complete* transitive closure of the root package as a single-version
solution. That is exactly what a Bazel consumer needs, because Dart resolution
at build time runs off the assembled `.pub_cache` plus
`.dart_tool/package_config.json` — Bazel edges exist only so that
`transitive_pub_caches` reaches every package's payload.

So each hosted package becomes a leaf repository with no deps of its own, and
one hub per lock carries the closure:

    @<hub>//:all       # every package in the lock, for a library's `deps`
    @<hub>//:<package> # alias to the individual leaf, when a narrower dep is
                       # genuinely wanted

Hub-to-leaf is acyclic by construction, so the cycle pruning that the pub
universe used to force on us (dio <-> dio_web_adapter and friends) is gone.
"""

_BUILD_HEADER = """\
# Generated by rules_flutter from {origin}. Do not edit.
load("@rules_flutter//flutter:defs.bzl", "dart_library")

package(default_visibility = ["//visibility:public"])

"""

def _pub_lock_hub_impl(repository_ctx):
    spokes = repository_ctx.attr.spokes
    packages = sorted(spokes.keys())

    lines = [_BUILD_HEADER.format(origin = repository_ctx.attr.origin)]

    # `all` carries the whole closure. It has no sources and no pubspec: a
    # dart_library in that shape is a pure aggregator of transitive_pub_caches.
    lines.append("dart_library(\n    name = \"all\",\n    deps = [\n")
    for package in packages:
        lines.append("        \"@{}//:{}\",\n".format(spokes[package], package))
    lines.append("    ],\n)\n\n")

    for package in packages:
        lines.append(
            "alias(\n    name = \"{}\",\n    actual = \"@{}//:{}\",\n)\n\n".format(
                package,
                spokes[package],
                package,
            ),
        )

    repository_ctx.file("BUILD.bazel", "".join(lines), executable = False)

pub_lock_hub = repository_rule(
    implementation = _pub_lock_hub_impl,
    attrs = {
        "origin": attr.string(
            doc = "Label of the pubspec.lock this hub was generated from, for diagnostics.",
            mandatory = True,
        ),
        "spokes": attr.string_dict(
            doc = "Package name to the leaf repository holding that package.",
            mandatory = True,
        ),
    },
    doc = "Emits aliases and an `:all` aggregate for one pubspec.lock's package closure.",
)
