"""Creates a repository alias that always exposes the host Flutter SDK.


The repository mirrors the contents of the platform-specific Flutter SDK
selected for the current host machine so that clients can uniformly depend
on `@<name>_sdk` (e.g. `@flutter_sdk`) without caring about the underlying
platform repository name.
"""

load(":repo_names.bzl", "sibling_canonical_repo")

def _is_arm64(repository_ctx):
    """True when the host CPU is 64-bit ARM."""
    return repository_ctx.os.arch.lower() in ["aarch64", "arm64"]

def _host_platform(repository_ctx):
    """Normalize the Bazel host OS/CPU to a Flutter platform suffix.

    Linux and macOS distinguish architectures; Flutter ships no Windows-on-ARM
    release. The macOS archive is *not* a universal binary — Flutter publishes
    flutter_macos_<v> and flutter_macos_arm64_<v> side by side, and taking the
    x64 one on Apple silicon runs the whole toolchain under Rosetta.
    """
    lower_name = repository_ctx.os.name.lower()
    if lower_name.startswith("mac"):
        return "macos_arm64" if _is_arm64(repository_ctx) else "macos"
    if lower_name.startswith("linux"):
        return "linux_arm64" if _is_arm64(repository_ctx) else "linux"
    if lower_name.startswith("windows"):
        return "windows"
    fail("Unsupported host platform '{}'. Expected macOS, Linux, or Windows.".format(repository_ctx.os.name))

def _sdk_repo_impl(repository_ctx):
    platform = _host_platform(repository_ctx)
    target_repo = "{}_{}".format(repository_ctx.attr.user_repository_name, platform)

    canonical_target_repo = _canonical_target_repo(repository_ctx.name, target_repo)
    build_label = Label("@@{}//:BUILD.bazel".format(canonical_target_repo))
    build_path = repository_ctx.path(build_label)
    if not build_path.exists:
        fail("Unable to locate Flutter SDK repository '{}' for host platform '{}'".format(target_repo, platform))

    _write_binary_symlinks(repository_ctx, canonical_target_repo)
    _write_root_aliases(repository_ctx, canonical_target_repo)
    _write_package_aliases(repository_ctx, build_path.dirname, canonical_target_repo)

    repository_ctx.file(
        "HOST_PLATFORM",
        "rules_flutter host SDK alias for {}\n".format(platform),
    )

def _canonical_target_repo(current_repo_name, target_repo):
    """Return the canonical repo name for target_repo within this extension."""

    return sibling_canonical_repo(current_repo_name, target_repo)

def _write_binary_symlinks(repository_ctx, canonical_target_repo):
    """Create platform-agnostic symlinks to dart/flutter binaries.

    These symlinks allow shell scripts to use stable rlocation paths like:
    - rules_flutter++flutter+flutter_sdk/bin/dart
    - rules_flutter++flutter+flutter_sdk/bin/flutter
    """
    platform = _host_platform(repository_ctx)

    if platform == "windows":
        dart_name = "dart.exe"
        flutter_name = "flutter.bat"
    else:
        dart_name = "dart"
        flutter_name = "flutter"

    # Create symlinks to the actual binaries in the platform-specific repo
    repository_ctx.symlink(
        Label("@@{}//:flutter/bin/{}".format(canonical_target_repo, dart_name)),
        "bin/dart",
    )
    repository_ctx.symlink(
        Label("@@{}//:flutter/bin/{}".format(canonical_target_repo, flutter_name)),
        "bin/flutter",
    )

def _write_root_aliases(repository_ctx, canonical_target_repo):
    """Emit aliases for top-level targets provided by the SDK repository."""

    content = """# Generated by rules_flutter//flutter/private:sdk_repo.bzl

# Platform-agnostic binary targets that use select() to pick the right binary.
alias(
    name = "flutter",
    actual = select({{
        "@platforms//os:windows": ":flutter_binary_windows",
        "//conditions:default": ":flutter_binary_unix",
    }}),
    visibility = ["//visibility:public"],
)

alias(
    name = "dart",
    actual = select({{
        "@platforms//os:windows": ":dart_binary_windows",
        "//conditions:default": ":dart_binary_unix",
    }}),
    visibility = ["//visibility:public"],
)

alias(
    name = "flutter_binary_unix",
    actual = "@@{repo}//:flutter_binary_unix",
    visibility = ["//visibility:public"],
)

alias(
    name = "flutter_binary_windows",
    actual = "@@{repo}//:flutter_binary_windows",
    visibility = ["//visibility:public"],
)

alias(
    name = "dart_binary_unix",
    actual = "@@{repo}//:dart_binary_unix",
    visibility = ["//visibility:public"],
)

alias(
    name = "dart_binary_windows",
    actual = "@@{repo}//:dart_binary_windows",
    visibility = ["//visibility:public"],
)

alias(
    name = "flutter_sdk",
    actual = "@@{repo}//:flutter_sdk",
    visibility = ["//visibility:public"],
)

# Platform-agnostic binary symlinks for shell scripts
# Use rlocation("rules_flutter++flutter+flutter_sdk/bin/dart") to find these
filegroup(
    name = "dart_bin",
    srcs = ["bin/dart"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "flutter_bin",
    srcs = ["bin/flutter"],
    visibility = ["//visibility:public"],
)

alias(
    name = "flutter_toolchain",
    actual = "@@{repo}//:flutter_toolchain",
    visibility = ["//visibility:public"],
)
""".format(
        repo = canonical_target_repo,
    )

    repository_ctx.file("BUILD.bazel", content)

def _write_package_aliases(repository_ctx, host_root, canonical_target_repo):
    """Create alias BUILD files for Flutter SDK packages."""

    for rel_root in ["flutter/packages", "flutter/bin/cache/pkg"]:
        host_dir = _path_join(host_root, rel_root)
        if not host_dir.exists or not host_dir.is_dir:
            continue

        for entry in host_dir.readdir():
            if not entry.is_dir:
                continue
            if not entry.get_child("pubspec.yaml").exists:
                continue

            package = entry.basename
            rel_dir = "{}/{}".format(rel_root, package)
            content = """# Generated alias for {package}
alias(
    name = "{package}",
    actual = "@@{repo}//{rel_dir}:{package}",
    visibility = ["//visibility:public"],
)
""".format(
                package = package,
                repo = canonical_target_repo,
                rel_dir = rel_dir,
            )
            repository_ctx.file("{}/BUILD.bazel".format(rel_dir), content)

def _path_join(root, rel_path):
    """Return a Path for rel_path under root (without touching the filesystem)."""

    current = root
    for component in rel_path.split("/"):
        if not component:
            continue
        current = current.get_child(component)
    return current

flutter_sdk_repo = repository_rule(
    implementation = _sdk_repo_impl,
    attrs = {
        "user_repository_name": attr.string(
            doc = "Base repository name used when registering Flutter toolchains.",
            mandatory = True,
        ),
    },
    doc = "Creates a host-aware alias repository exposing the Flutter SDK.",
)
