"""Create a repository to hold the toolchains

This follows guidance here:
https://docs.bazel.build/versions/main/skylark/deploying.html#registering-toolchains
"
Note that in order to resolve toolchains in the analysis phase
Bazel needs to analyze all toolchain targets that are registered.
Bazel will not need to analyze all targets referenced by toolchain.toolchain attribute.
If in order to register toolchains you need to perform complex computation in the repository,
consider splitting the repository with toolchain targets
from the repository with <LANG>_toolchain targets.
Former will be always fetched,
and the latter will only be fetched when user actually needs to build <LANG> code.
"
The "complex computation" in our case is simply downloading large artifacts.
This guidance tells us how to avoid that: we put the toolchain targets in the alias repository
with only the toolchain attribute pointing into the platform-specific repositories.
"""

load(":repo_names.bzl", "sibling_canonical_repo")

# Add more platforms as needed to mirror all the binaries
# published by Flutter SDK releases.
PLATFORMS = {
    "macos": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    # Flutter publishes a native macos-arm64 archive (flutter_macos_arm64_*)
    # in the same release directory as the x64 one, so unlike linux_arm64 this
    # needs no re-architecting. Until it was registered, `macos` carried no cpu
    # constraint and Apple silicon resolved to the x64 SDK — which works only
    # through Rosetta, and builds an x64 engine on an arm64 machine.
    "macos_arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:arm64",
        ],
    ),
    "linux": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    # Flutter publishes no linux-arm64 SDK archive, but it does publish
    # linux-arm64 engine artifacts and a linux-arm64 Dart SDK. This platform
    # reuses the x64 release archive (framework sources, flutter_tools, and
    # templates are architecture-independent) and swaps the architecture-
    # specific parts of bin/cache. See _rearchitect_linux_arm64 in
    # repositories.bzl.
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:arm64",
        ],
    ),
    "windows": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
}

def _toolchains_repo_impl(repository_ctx):

    build_content = """# Generated by toolchains_repo.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the flutter_register_toolchains macro
# so you don't normally need to interact with these targets.

"""

    for [platform, meta] in PLATFORMS.items():
        canonical_target_repo = sibling_canonical_repo(
            repository_ctx.name,
            "{}_{}".format(repository_ctx.attr.user_repository_name, platform),
        )
        build_content += """
# Declare a toolchain Bazel will select for running the tool in an action
# on the execution platform.
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@@{target_repo}//:flutter_toolchain",
    toolchain_type = "@rules_flutter//flutter:toolchain_type",
)
""".format(
            platform = platform,
            target_repo = canonical_target_repo,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "what the user chose for the base name"),
    },
)
