import 'package:fixnum/fixnum.dart';
import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:flutter/widget_previews.dart';
import 'package:hello_world/generated/l10n.dart';
// Generated by dart_proto_library and mounted via generated_srcs.
import 'package:hello_world/generated/api/v1/service.pb.dart';
import 'package:material_ui/material_ui.dart';

// Code generation via intl_utils is configured in this project.
// ARB files are in l10n/ and generated files will be emitted into
// lib/generated/ after running 'flutter pub run intl_utils:generate'.

// Injected by the flutter_app dart_defines attribute; rendered below so the
// constant survives tree shaking and the e2e test can assert on the bundle.
const String smokeDefine = String.fromEnvironment(
  'SMOKE_DEFINE',
  defaultValue: 'smoke-define-unset',
);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateTitle: (context) => S.of(context).appTitle,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      localizationsDelegates: [
        S.delegate,
        ...GlobalMaterialLocalizations.delegates,
      ],
      supportedLocales: S.delegate.supportedLocales,
      home: const MyHomePage(),
    );
  }
}

@Preview(name: 'Material counter button', group: 'Standalone UI')
Widget materialButtonPreview() =>
    FloatingActionButton(onPressed: () {}, child: const Icon(Icons.add));

@Preview(name: 'Cupertino action', group: 'Standalone UI')
Widget cupertinoButtonPreview() =>
    CupertinoButton(onPressed: () {}, child: const Text('Preview Cupertino'));

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // Use fixnum to exercise dependency resolution in the smoke test.
  Int64 _counter = Int64.ZERO;

  void _incrementCounter() {
    setState(() {
      _counter += Int64.ONE;
    });
  }

  @override
  Widget build(BuildContext context) {
    final strings = S.of(context);

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(strings.homePageTitle),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(strings.buttonPushedMessage),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const Text(smokeDefine),
            // Exercises the mounted proto-generated code.
            Text((GreetingResponse()..message = smokeDefine).message),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: strings.incrementTooltip,
        child: const Icon(Icons.add),
      ),
    );
  }
}
