"""Unit tests for the `pubspec.lock` parser.

The parser takes a string rather than a Label, so every fixture below is an
inline literal — no file I/O and no repository rule is involved.
"""

load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load("//flutter/private:package_generation.bzl", "parse_pubspec_sdk_flutter_dependencies")
load(
    "//flutter/private:pubspec_lock.bzl",
    "lock_direct_packages",
    "lock_hosted_packages",
    "parse_lock_sdk_constraints",
    "parse_pubspec_lock",
)

# A lock covering every source pub can emit, plus the quoting variations it
# uses in practice: sha256 values are quoted only when they start with a digit,
# and versions are always quoted while `source` never is.
_LOCK = """# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: a1ace0a0f0f0e0d0c0b0a09080706050403020100fedcba9876543210abcdef01
      url: 'https://pub.dev'
    source: hosted
    version: "5.0.0"
  local_widget:
    dependency: "direct main"
    description:
      path: "../local_widget"
      relative: "true"
    source: path
    version: "0.1.0"
  sky_engine:
    dependency: transitive
    description: dart
    source: sdk
    version: "0.0.99"

sdks:
  dart: ">=3.9.0-0 <4.0.0"
  flutter: ">=3.24.0"
"""

def _hosted_test_impl(ctx):
    env = unittest.begin(ctx)
    packages = parse_pubspec_lock(_LOCK)

    collection = packages["collection"]
    asserts.equals(env, "collection", collection.name)
    asserts.equals(env, "hosted", collection.source)
    asserts.equals(env, "transitive", collection.dependency)
    asserts.equals(env, "1.19.1", collection.version)
    asserts.equals(env, "https://pub.dev", collection.url)
    asserts.equals(
        env,
        "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76",
        collection.sha256,
    )

    # Unquoted sha256 and single-quoted url parse identically to the quoted form.
    lints = packages["flutter_lints"]
    asserts.equals(
        env,
        "a1ace0a0f0f0e0d0c0b0a09080706050403020100fedcba9876543210abcdef01",
        lints.sha256,
    )
    asserts.equals(env, "https://pub.dev", lints.url)
    asserts.equals(env, "direct dev", lints.dependency)
    return unittest.end(env)

def _scalar_description_test_impl(ctx):
    env = unittest.begin(ctx)
    packages = parse_pubspec_lock(_LOCK)

    # `description: flutter` / `description: dart` are bare scalars, not maps.
    for name, scalar in [("flutter", "flutter"), ("sky_engine", "dart")]:
        pkg = packages[name]
        asserts.equals(env, "sdk", pkg.source)
        asserts.equals(env, scalar, pkg.description_scalar)
        asserts.equals(env, {}, pkg.description)
        asserts.equals(env, "", pkg.url)
        asserts.equals(env, "", pkg.sha256)
    return unittest.end(env)

def _path_dependency_test_impl(ctx):
    env = unittest.begin(ctx)
    pkg = parse_pubspec_lock(_LOCK)["local_widget"]
    asserts.equals(env, "path", pkg.source)
    asserts.equals(env, "../local_widget", pkg.path)
    asserts.equals(env, "true", pkg.description["relative"])
    asserts.equals(env, "", pkg.description_scalar)
    return unittest.end(env)

def _git_dependency_test_impl(ctx):
    env = unittest.begin(ctx)
    packages = parse_pubspec_lock("""packages:
  vendored:
    dependency: "direct main"
    description:
      path: "packages/vendored"
      ref: main
      resolved-ref: "0123456789abcdef0123456789abcdef01234567"
      url: "https://github.com/example/repo.git"
    source: git
    version: "2.0.0"
""")
    pkg = packages["vendored"]
    asserts.equals(env, "git", pkg.source)
    asserts.equals(env, "https://github.com/example/repo.git", pkg.url)
    asserts.equals(env, "packages/vendored", pkg.path)
    asserts.equals(env, "main", pkg.description["ref"])
    asserts.equals(
        env,
        "0123456789abcdef0123456789abcdef01234567",
        pkg.description["resolved-ref"],
    )
    return unittest.end(env)

def _sdks_test_impl(ctx):
    env = unittest.begin(ctx)
    sdks = parse_lock_sdk_constraints(_LOCK)
    asserts.equals(env, ">=3.9.0-0 <4.0.0", sdks["dart"])
    asserts.equals(env, ">=3.24.0", sdks["flutter"])

    # A lock with no `sdks:` block yields an empty dict, not a failure.
    asserts.equals(env, {}, parse_lock_sdk_constraints("packages: {}\n"))
    return unittest.end(env)

def _empty_lock_test_impl(ctx):
    env = unittest.begin(ctx)
    asserts.equals(env, {}, parse_pubspec_lock("packages: {}\nsdks:\n  dart: any\n"))
    return unittest.end(env)

def _filters_test_impl(ctx):
    env = unittest.begin(ctx)
    packages = parse_pubspec_lock(_LOCK)

    # Hosted excludes sdk and path sources; direct excludes transitive ones.
    asserts.equals(
        env,
        ["collection", "flutter_lints"],
        sorted(lock_hosted_packages(packages).keys()),
    )
    asserts.equals(
        env,
        ["flutter", "flutter_lints", "local_widget"],
        sorted(lock_direct_packages(packages).keys()),
    )
    return unittest.end(env)

def _lockless_sdk_pubspec_test_impl(ctx):
    env = unittest.begin(ctx)
    asserts.equals(
        env,
        ["sky_engine"],
        parse_pubspec_sdk_flutter_dependencies("""name: flutter_gpu
dependencies:
  collection: 1.19.1
  sky_engine:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
"""),
    )
    return unittest.end(env)

# The unittest library requires that we export the test cases as named test
# rules, but their names are arbitrary and don't appear anywhere.
_t0_test = unittest.make(_hosted_test_impl)
_t1_test = unittest.make(_scalar_description_test_impl)
_t2_test = unittest.make(_path_dependency_test_impl)
_t3_test = unittest.make(_git_dependency_test_impl)
_t4_test = unittest.make(_sdks_test_impl)
_t5_test = unittest.make(_empty_lock_test_impl)
_t6_test = unittest.make(_filters_test_impl)
_t7_test = unittest.make(_lockless_sdk_pubspec_test_impl)

def pubspec_lock_test_suite(name):
    unittest.suite(name, _t0_test, _t1_test, _t2_test, _t3_test, _t4_test, _t5_test, _t6_test, _t7_test)
